services:
  flaskdash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flaskdash
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./extensions:/app/extensions
      - ./core/static/uploads:/app/core/static/uploads
      - ./themes:/app/themes
      - ./media:/app/media
    depends_on:
      frontend-build:
        condition: service_completed_successfully
  frontend-build:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm ci && npm run build"