target-version = "py312"

exclude = [
    "**/migrations/**",
    "core/route.py",
    "**/__init__.py",
    "extensions/**"
]

[lint]
select = ["F"]

[format]    
# Use tabs instead of 4 space indentation.
indent-style = "tab"