GRID_COLS_MAP = {
    1: "grid-cols-1",
    2: "grid-cols-2",
    3: "grid-cols-3",
    4: "grid-cols-4",
    5: "grid-cols-5",
    6: "grid-cols-6",
    7: "grid-cols-7",
    8: "grid-cols-8",
    9: "grid-cols-9",
    10: "grid-cols-10",
    11: "grid-cols-11",
    12: "grid-cols-12",
}

GRID_ROWS_MAP = {
    1: "grid-rows-1",
    2: "grid-rows-2",
    3: "grid-rows-3",
    4: "grid-rows-4",
    5: "grid-rows-5",
    6: "grid-rows-6",
}

COL_SPAN_MAP = {
    1: "col-span-1",
    2: "col-span-2",
    3: "col-span-3",
    4: "col-span-4",
    5: "col-span-5",
    6: "col-span-6",
    7: "col-span-7",
    8: "col-span-8",
    9: "col-span-9",
    10: "col-span-10",
    11: "col-span-11",
    12: "col-span-12",
    "full": "col-span-full",
}

ROW_SPAN_MAP = {
    1: "row-span-1",
    2: "row-span-2",
    3: "row-span-3",
    4: "row-span-4",
    5: "row-span-5",
    6: "row-span-6",
    "full": "row-span-full",
}

RESPONSIVE_GRID_COLS_MAP = {
    "sm": {
        1: "sm:grid-cols-1",
        2: "sm:grid-cols-2",
        3: "sm:grid-cols-3",
        4: "sm:grid-cols-4",
        5: "sm:grid-cols-5",
        6: "sm:grid-cols-6",
        7: "sm:grid-cols-7",
        8: "sm:grid-cols-8",
        9: "sm:grid-cols-9",
        10: "sm:grid-cols-10",
        11: "sm:grid-cols-11",
        12: "sm:grid-cols-12",
    },
    "md": {
        1: "md:grid-cols-1",
        2: "md:grid-cols-2",
        3: "md:grid-cols-3",
        4: "md:grid-cols-4",
        5: "md:grid-cols-5",
        6: "md:grid-cols-6",
        7: "md:grid-cols-7",
        8: "md:grid-cols-8",
        9: "md:grid-cols-9",
        10: "md:grid-cols-10",
        11: "md:grid-cols-11",
        12: "md:grid-cols-12",
    },
    "lg": {
        1: "lg:grid-cols-1",
        2: "lg:grid-cols-2",
        3: "lg:grid-cols-3",
        4: "lg:grid-cols-4",
        5: "lg:grid-cols-5",
        6: "lg:grid-cols-6",
        7: "lg:grid-cols-7",
        8: "lg:grid-cols-8",
        9: "lg:grid-cols-9",
        10: "lg:grid-cols-10",
        11: "lg:grid-cols-11",
        12: "lg:grid-cols-12",
    },
    "xl": {
        1: "xl:grid-cols-1",
        2: "xl:grid-cols-2",
        3: "xl:grid-cols-3",
        4: "xl:grid-cols-4",
        5: "xl:grid-cols-5",
        6: "xl:grid-cols-6",
        7: "xl:grid-cols-7",
        8: "xl:grid-cols-8",
        9: "xl:grid-cols-9",
        10: "xl:grid-cols-10",
        11: "xl:grid-cols-11",
        12: "xl:grid-cols-12",
    }
}

RESPONSIVE_GRID_ROWS_MAP = {
    "sm": {
        1: "sm:grid-rows-1",
        2: "sm:grid-rows-2",
        3: "sm:grid-rows-3",
        4: "sm:grid-rows-4",
        5: "sm:grid-rows-5",
        6: "sm:grid-rows-6",
    },
    "md": {
        1: "md:grid-rows-1",
        2: "md:grid-rows-2",
        3: "md:grid-rows-3",
        4: "md:grid-rows-4",
        5: "md:grid-rows-5",
        6: "md:grid-rows-6",
    },
    "lg": {
        1: "lg:grid-rows-1",
        2: "lg:grid-rows-2",
        3: "lg:grid-rows-3",
        4: "lg:grid-rows-4",
        5: "lg:grid-rows-5",
        6: "lg:grid-rows-6",
    },
    "xl": {
        1: "xl:grid-rows-1",
        2: "xl:grid-rows-2",
        3: "xl:grid-rows-3",
        4: "xl:grid-rows-4",
        5: "xl:grid-rows-5",
        6: "xl:grid-rows-6",
    }
}

RESPONSIVE_COL_SPAN_MAP = {
    "sm": {
        1: "sm:col-span-1",
        2: "sm:col-span-2",
        3: "sm:col-span-3",
        4: "sm:col-span-4",
        5: "sm:col-span-5",
        6: "sm:col-span-6",
        7: "sm:col-span-7",
        8: "sm:col-span-8",
        9: "sm:col-span-9",
        10: "sm:col-span-10",
        11: "sm:col-span-11",
        12: "sm:col-span-12",
        "full": "sm:col-span-full",
    },
    "md": {
        1: "md:col-span-1",
        2: "md:col-span-2",
        3: "md:col-span-3",
        4: "md:col-span-4",
        5: "md:col-span-5",
        6: "md:col-span-6",
        7: "md:col-span-7",
        8: "md:col-span-8",
        9: "md:col-span-9",
        10: "md:col-span-10",
        11: "md:col-span-11",
        12: "md:col-span-12",
        "full": "md:col-span-full",
    },
    "lg": {
        1: "lg:col-span-1",
        2: "lg:col-span-2",
        3: "lg:col-span-3",
        4: "lg:col-span-4",
        5: "lg:col-span-5",
        6: "lg:col-span-6",
        7: "lg:col-span-7",
        8: "lg:col-span-8",
        9: "lg:col-span-9",
        10: "lg:col-span-10",
        11: "lg:col-span-11",
        12: "lg:col-span-12",
        "full": "lg:col-span-full",
    },
    "xl": {
        1: "xl:col-span-1",
        2: "xl:col-span-2",
        3: "xl:col-span-3",
        4: "xl:col-span-4",
        5: "xl:col-span-5",
        6: "xl:col-span-6",
        7: "xl:col-span-7",
        8: "xl:col-span-8",
        9: "xl:col-span-9",
        10: "xl:col-span-10",
        11: "xl:col-span-11",
        12: "xl:col-span-12",
        "full": "xl:col-span-full",
    }
}

RESPONSIVE_ROW_SPAN_MAP = {
    "sm": {
        1: "sm:row-span-1",
        2: "sm:row-span-2",
        3: "sm:row-span-3",
        4: "sm:row-span-4",
        5: "sm:row-span-5",
        6: "sm:row-span-6",
        "full": "sm:row-span-full",
    },
    "md": {
        1: "md:row-span-1",
        2: "md:row-span-2",
        3: "md:row-span-3",
        4: "md:row-span-4",
        5: "md:row-span-5",
        6: "md:row-span-6",
        "full": "md:row-span-full",
    },
    "lg": {
        1: "lg:row-span-1",
        2: "lg:row-span-2",
        3: "lg:row-span-3",
        4: "lg:row-span-4",
        5: "lg:row-span-5",
        6: "lg:row-span-6",
        "full": "lg:row-span-full",
    },
    "xl": {
        1: "xl:row-span-1",
        2: "xl:row-span-2",
        3: "xl:row-span-3",
        4: "xl:row-span-4",
        5: "xl:row-span-5",
        6: "xl:row-span-6",
        "full": "xl:row-span-full",
    }
}