"""cascade login history

Revision ID: 026b9e12e2c2
Revises: 7c328fe6b82a
Create Date: 2026-06-23 11:03:04.738886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026b9e12e2c2'
down_revision = '7c328fe6b82a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('login_history_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.drop_constraint('login_history_ibfk_1', type_='foreignkey')  
        batch_op.create_foreign_key(
            batch_op.f('login_history_ibfk_1'), 'user', ['user_id'], ['id']
        )
    # ### end Alembic commands ###