"""setting value nullable

Revision ID: e43d481c6c8e
Revises: 026b9e12e2c2
Create Date: 2026-07-20 17:23:55.491476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e43d481c6c8e'
down_revision = '026b9e12e2c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version_landing_page')
    op.drop_table('user_roles')
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)

    op.create_table('user_roles',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('user_roles_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('user_roles_ibfk_1')),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('alembic_version_landing_page',
    sa.Column('version_num', mysql.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('version_num'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
